[project]
name = "buddhi-ai-studio"
version = "0.0.1"
description = "Buddhi AI Studio is an AI Agent Development Environment"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.0",
    "uvicorn[standard]>=0.40.0",
    "huggingface_hub>=1.7.2",
    "sqlalchemy>=2.0.48",
    "alembic>=1.18.4",
    "python-dotenv>=1.2.2",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.13.1",
    "llama-cpp-python>=0.3.16",
]
